### ISSUE TITLE
[BUG] Wheels publishing broken

### ISSUE THREAD

**Issue by gmarkall** [NVIDIA/numba-cuda#75]
**Describe the bug**

Publishing wheels to PyPI is not working - see e.g. https://github.com/NVIDIA/numba-cuda/actions/runs/12087281889

The suggested workflow would be to upload the package on the self-hosted runner, then use a Github-hosted runner to download the package and publish it to PyPI: https://github.com/pypa/gh-action-pypi-publish/issues/300#issuecomment-2486084670

In the meantime I'm manually publishing wheels and sdists to PyPI.

**Steps/Code to reproduce bug**

Push a tag so that the publishing workflow kicks off. Unfortunately we can only do this when we release a new version, so it's mildly inconvenient to test.

**Comment by webknjaz** [comment]
> In the meantime I'm manually publishing wheels and sdists to PyPI.

Note that this won't let you produce attestations that are auto-created with the action.

> The suggested workflow would be to upload the package on the self-hosted runner, then use a Github-hosted runner to download the package and publish it to PyPI:

I would even say that it's the only one truly supported.

**Comment by gmarkall** [comment]
@webknjaz Thanks for the pointers - will follow up if I run into further issues / confusion! 🙂

**Comment by leofang** [comment]
This part from the CI log is confusing
```
Run # Create Docker container action
  # Create Docker container action
  /pyenv/shims/python3 '/home/runner/_work/_actions/pypa/gh-action-pypi-publish/release/v1/create-docker-action.py'
  shell: bash --noprofile --norc -e -o pipefail {0}
  env:
    RAPIDS_ARTIFACTS_DIR: /home/runner/_work/numba-cuda/numba-cuda/artifacts
    RAPIDS_REPOSITORY: NVIDIA/numba-cuda
    RAPIDS_SHA: 793d2389d64b0c56166bc034752baea9a3224254
    RAPIDS_REF_NAME: v0.0.19
    RAPIDS_NIGHTLY_DATE: 
    wheel_path: /__w/numba-cuda/numba-cuda/dist/numba_cuda-0.0.19-py3-none-any.whl
    sdist_path: /__w/numba-cuda/numba-cuda/dist/numba_cuda-0.0.19.tar.gz
    REF: release/v1
    REPO: pypa/gh-action-pypi-publish
    REPO_ID: 803332719
/pyenv/versions/3.12.6/bin/python3: can't open file '/home/runner/_work/_actions/pypa/gh-action-pypi-publish/release/v1/create-docker-action.py': [Errno 2] No such file or directory
```
I checked `pypa/gh-action-pypi-publish/release/v1/create-docker-action.py` is still there:
https://github.com/pypa/gh-action-pypi-publish/blob/release/v1/create-docker-action.py
I am not convinced this is a self-hosted runner issue...
